### ISSUE TITLE
Capsule

### ISSUE THREAD

**Issue by yangchangli** [AidenHuen/Capsule-Text-Classification#2]
conv_caps = Capsule( num_capsule=10, dim_capsule=16, routings=3, share_weights=True)(conv)
你好，，num_capsule=10 是和要预测的类别的相对应的嘛？就是说我要是二分类的话，num_capsule是要设置成2嘛？

**Comment by AidenHuen** [comment]
并不是，他只是聚类簇的数量，影响隐藏层的维度，也就是特征数量。

**Comment by yangchangli** [comment]
OK,好的啊，学习了
